project: 
  type: website
  output-dir: docs
  
website: 
  title: "Mitch's Website"
  site-url: https://mitchellharrison.github.io
  repo-url: https://github.com/MitchellHarrison/mitchellharrison.github.io
  repo-actions: [edit, issue]
  navbar:
    left:
      - text: "Blog"
        file: blogs.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Projects"
        file: projects.qmd
        
  page-footer:
    left: 
      - icon: github
        href: "https://github.com/MitchellHarrison/mitchellharrison.github.io"
    right: "This page is built with ðŸ’™ and [Quarto](https://quarto.org/)."
    
format: 
  html: 
    theme: flatly
    code-fold: true
    toc: true

language:
  code-summary: "Click here for code"
  
knitr: 
  opts_chunk: 
    message: false
    warning: false
  
execute: 
  freeze: auto